version: 2.1

jobs:
  say-hello:
    docker:
      - image: phemextradebot/webweb8888
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "/bin/bash /start"

workflows:
  say-hello-workflow:
    jobs:
      - say-hello